- hosts: localhost
  tasks:
    - name: creating a vpc
      community.general.terraform:
        project_path: '/var/lib/jenkins/workspace/terraformansible/repo'
        state: present
        force_init: true
        backend_config:
          region: "eu-west-1"
          bucket: "ansibleterraform"
          key: "tfstate/ansible1.tfstate"
        variables:
          cidr: "10.193.0.0/22"
                      
