- hosts: localhost
  tasks:
    - name: cd to working directory
      command: cd /var/lib/jenkins/workspace/terraformansible/repo
    - name: creating plan file
      command: sh (terraform plan -no-color | out planfile)
    - name: creating a vpc
      community.general.terraform:
        project_path: '/var/lib/jenkins/workspace/terraformansible/repo'
        state: "{{ state_var }}"
        force_init: true
        plan_file: '/var/lib/jenkins/workspace/terraformansible/repo/planfile'
        backend_config:
          region: "eu-west-1"
          bucket: "ansibleterraform"
          key: "tfstate/ansible1.tfstate"
        variables:
          cidr: "10.196.0.0/22"
                      
